/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 myroom.glb
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Wall0: THREE.Mesh
    Window0003: THREE.Mesh
    Door0: THREE.Mesh
    Wall10: THREE.Mesh
    Wall12: THREE.Mesh
    Wall14: THREE.Mesh
    Wall15: THREE.Mesh
    Wall16: THREE.Mesh
    Wall18: THREE.Mesh
    Wall19: THREE.Mesh
    Wall1: THREE.Mesh
    Wall20: THREE.Mesh
    Wall21: THREE.Mesh
    Wall22: THREE.Mesh
    Wall23: THREE.Mesh
    Wall24: THREE.Mesh
    Window0001: THREE.Mesh
    Wall25: THREE.Mesh
    Window0: THREE.Mesh
    Wall26: THREE.Mesh
    Wall27: THREE.Mesh
    Wall28: THREE.Mesh
    Wall29: THREE.Mesh
    Wall2: THREE.Mesh
    Wall30: THREE.Mesh
    Wall31: THREE.Mesh
    Opening0004: THREE.Mesh
    Wall32: THREE.Mesh
    Door0002: THREE.Mesh
    Wall33: THREE.Mesh
    Opening0: THREE.Mesh
    Wall34: THREE.Mesh
    Opening0001: THREE.Mesh
    Wall35: THREE.Mesh
    Door0001: THREE.Mesh
    Wall36: THREE.Mesh
    Opening0002: THREE.Mesh
    Wall37: THREE.Mesh
    Window0002: THREE.Mesh
    Opening0003: THREE.Mesh
    Wall38: THREE.Mesh
    Wall3: THREE.Mesh
    Wall4: THREE.Mesh
    Wall5: THREE.Mesh
    Wall6: THREE.Mesh
    Wall7: THREE.Mesh
    Wall8: THREE.Mesh
    Wall9: THREE.Mesh
    Bed0: THREE.Mesh
    Chair0: THREE.Mesh
    Chair1: THREE.Mesh
    Chair2: THREE.Mesh
    Chair3: THREE.Mesh
    Dishwasher0: THREE.Mesh
    Oven0: THREE.Mesh
    Refrigerator0: THREE.Mesh
    Sink0: THREE.Mesh
    Sofa0: THREE.Mesh
    Sofa1: THREE.Mesh
    Sofa2: THREE.Mesh
    Storage0: THREE.Mesh
    Storage1: THREE.Mesh
    Storage10: THREE.Mesh
    Storage11: THREE.Mesh
    Storage12: THREE.Mesh
    Storage13: THREE.Mesh
    Storage2: THREE.Mesh
    Storage3: THREE.Mesh
    Storage4: THREE.Mesh
    Storage5: THREE.Mesh
    Storage6: THREE.Mesh
    Storage7: THREE.Mesh
    Storage8: THREE.Mesh
    Storage9: THREE.Mesh
    Table0: THREE.Mesh
    Table1: THREE.Mesh
    Table2: THREE.Mesh
    Table3: THREE.Mesh
    Table4: THREE.Mesh
    Table5: THREE.Mesh
    Table6: THREE.Mesh
    Television0: THREE.Mesh
    Television1: THREE.Mesh
    Television2: THREE.Mesh
    Washerdryer0: THREE.Mesh
  }
  materials: {
    Wall0_color: THREE.MeshStandardMaterial
    Window0_color: THREE.MeshStandardMaterial
    Door0_color: THREE.MeshStandardMaterial
    Wall10_color: THREE.MeshStandardMaterial
    Wall12_color: THREE.MeshStandardMaterial
    Wall14_color: THREE.MeshStandardMaterial
    Wall15_color: THREE.MeshStandardMaterial
    Wall16_color: THREE.MeshStandardMaterial
    Wall18_color: THREE.MeshStandardMaterial
    Wall19_color: THREE.MeshStandardMaterial
    Wall1_color: THREE.MeshStandardMaterial
    Wall20_color: THREE.MeshStandardMaterial
    Wall21_color: THREE.MeshStandardMaterial
    Wall22_color: THREE.MeshStandardMaterial
    Wall23_color: THREE.MeshStandardMaterial
    Wall24_color: THREE.MeshStandardMaterial
    Wall25_color: THREE.MeshStandardMaterial
    Wall26_color: THREE.MeshStandardMaterial
    Wall27_color: THREE.MeshStandardMaterial
    Wall28_color: THREE.MeshStandardMaterial
    Wall29_color: THREE.MeshStandardMaterial
    Wall2_color: THREE.MeshStandardMaterial
    Wall30_color: THREE.MeshStandardMaterial
    Wall31_color: THREE.MeshStandardMaterial
    Opening0_color: THREE.MeshStandardMaterial
    Wall32_color: THREE.MeshStandardMaterial
    Wall33_color: THREE.MeshStandardMaterial
    Wall34_color: THREE.MeshStandardMaterial
    Wall35_color: THREE.MeshStandardMaterial
    Wall36_color: THREE.MeshStandardMaterial
    Wall37_color: THREE.MeshStandardMaterial
    Wall38_color: THREE.MeshStandardMaterial
    Wall3_color: THREE.MeshStandardMaterial
    Wall4_color: THREE.MeshStandardMaterial
    Wall5_color: THREE.MeshStandardMaterial
    Wall6_color: THREE.MeshStandardMaterial
    Wall7_color: THREE.MeshStandardMaterial
    Wall8_color: THREE.MeshStandardMaterial
    Wall9_color: THREE.MeshStandardMaterial
    Bed0_color: THREE.MeshStandardMaterial
    Chair0_color: THREE.MeshStandardMaterial
    Chair1_color: THREE.MeshStandardMaterial
    Chair2_color: THREE.MeshStandardMaterial
    Chair3_color: THREE.MeshStandardMaterial
    Dishwasher0_color: THREE.MeshStandardMaterial
    Oven0_color: THREE.MeshStandardMaterial
    Refrigerator0_color: THREE.MeshStandardMaterial
    Sink0_color: THREE.MeshStandardMaterial
    Sofa0_color: THREE.MeshStandardMaterial
    Sofa1_color: THREE.MeshStandardMaterial
    Sofa2_color: THREE.MeshStandardMaterial
    Storage0_color: THREE.MeshStandardMaterial
    Storage1_color: THREE.MeshStandardMaterial
    Storage10_color: THREE.MeshStandardMaterial
    Storage11_color: THREE.MeshStandardMaterial
    Storage12_color: THREE.MeshStandardMaterial
    Storage13_color: THREE.MeshStandardMaterial
    Storage2_color: THREE.MeshStandardMaterial
    Storage3_color: THREE.MeshStandardMaterial
    Storage4_color: THREE.MeshStandardMaterial
    Storage5_color: THREE.MeshStandardMaterial
    Storage6_color: THREE.MeshStandardMaterial
    Storage7_color: THREE.MeshStandardMaterial
    Storage8_color: THREE.MeshStandardMaterial
    Storage9_color: THREE.MeshStandardMaterial
    Table0_color: THREE.MeshStandardMaterial
    Table1_color: THREE.MeshStandardMaterial
    Table2_color: THREE.MeshStandardMaterial
    Table3_color: THREE.MeshStandardMaterial
    Table4_color: THREE.MeshStandardMaterial
    Table5_color: THREE.MeshStandardMaterial
    Table6_color: THREE.MeshStandardMaterial
    Television0_color: THREE.MeshStandardMaterial
    Television1_color: THREE.MeshStandardMaterial
    Television2_color: THREE.MeshStandardMaterial
    Washerdryer0_color: THREE.MeshStandardMaterial
  }
}

type Props = {
  position?: [number, number, number];
  rotation?: [number, number, number];
};

export function MyApartment(props: Props) {
  const { nodes, materials } = useGLTF("/3d/myroom.glb") as GLTFResult;

  const wallMaterial = new THREE.MeshStandardMaterial({
    side: THREE.DoubleSide,
    color: "#a5e1ad",
    metalness: 0.1,
    roughness: 0.75,
    shadowSide: THREE.DoubleSide,
    transparent: true,
    opacity: 0.8,
  });

  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Wall0.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-9.22, 5.55, 0.21]}
          rotation={[0, 0, -2.24]}
          scale={[5.24, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Window0003.geometry}
          material={materials.Window0_color}
          position={[-9.26, 5.5, 0.2]}
          rotation={[0, 0, -2.24]}
          scale={[4.64, 0, 1.8]}
        />
        <mesh
          geometry={nodes.Door0.geometry}
          material={materials.Door0_color}
          position={[0.41, 0.41, 0.21]}
          rotation={[0, 0, 2.48]}
          scale={[1.8, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall10.geometry}
          material={wallMaterial}
          name="Wall"
          position={[0.41, 0.4, 0.21]}
          rotation={[0, 0, 2.48]}
          scale={[1.81, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall12.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-8.5, 1.64, 0.21]}
          rotation={[0, 0, 2.47]}
          scale={[1.5, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall14.geometry}
          material={wallMaterial}
          name="Wall"
          position={[1.61, 0.46, 0.21]}
          rotation={[0, 0, 0.9]}
          scale={[1.58, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall15.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-2.38, 1.65, 0.21]}
          rotation={[0, 0, -0.67]}
          scale={[0.3, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall16.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-2.6, 1.03, 0.21]}
          rotation={[0, 0, -0.99]}
          scale={[0.27, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall18.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-6.29, 0.69, 0.21]}
          rotation={[0, 0, 2.44]}
          scale={[0.94, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall19.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-4.95, 1.63, 0.21]}
          rotation={[0, 0, 0.9]}
          scale={[3.16, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall1.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-11.61, -2.83, 0.21]}
          rotation={[0, 0, -0.67]}
          scale={[4.69, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall20.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-6.09, 0.18, 0.21]}
          rotation={[0, 0, 0.9]}
          scale={[0.53, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall21.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-2.64, 1.51, 0.21]}
          rotation={[0, 0, 1.04]}
          scale={[0.55, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall22.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-5.33, 5.82, 0.21]}
          rotation={[0, 0, 2.48]}
          scale={[5.78, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall23.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-2.22, 3.38, 0.21]}
          rotation={[0, 0, 2.48]}
          scale={[2.13, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall24.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-11.03, 1.72, 0.21]}
          rotation={[0, 0, -2.22]}
          scale={[3.02, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Window0001.geometry}
          material={materials.Window0_color}
          position={[-11.12, 1.61, -0.06]}
          rotation={[0, 0, -2.22]}
          scale={[2.29, 0, 1.48]}
        />
        <mesh
          geometry={nodes.Wall25.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-12.7, -0.43, 0.21]}
          rotation={[0, 0, -2.24]}
          scale={[2.42, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Window0.geometry}
          material={materials.Window0_color}
          position={[-12.8, -0.55, -0.06]}
          rotation={[0, 0, -2.24]}
          scale={[1.63, 0, 1.41]}
        />
        <mesh
          geometry={nodes.Wall26.geometry}
          material={wallMaterial}
          name="Wall"
          position={[0.34, -1.14, 0.21]}
          rotation={[0, 0, 0.9]}
          scale={[0.39, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall27.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-3.21, -2.48, 0.21]}
          rotation={[0, 0, -0.67]}
          scale={[3.95, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall28.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-5.51, -0.64, 0.21]}
          rotation={[0, 0, -0.69]}
          scale={[1.93, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall29.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-3.77, 0.01, 0.21]}
          rotation={[0, 0, -2.24]}
          scale={[3.21, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall2.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-9.01, -3.33, 0.21]}
          rotation={[0, 0, 0.9]}
          scale={[2.42, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall30.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-1.09, 0.16, 0.21]}
          rotation={[0, 0, -2.23]}
          scale={[0.66, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall31.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-0.54, -0.7, 0.21]}
          rotation={[0, 0, -0.67]}
          scale={[1.92, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Opening0004.geometry}
          material={materials.Opening0_color}
          position={[-9.6, 2.52, 0.31]}
          rotation={[0, 0, -0.67]}
          scale={[1.31, 0, 2.34]}
        />
        <mesh
          geometry={nodes.Wall32.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-9.6, 2.52, 0.21]}
          rotation={[0, 0, -0.67]}
          scale={[1.31, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Door0002.geometry}
          material={materials.Door0_color}
          position={[-2.8, 1.97, 0.43]}
          rotation={[0, 0, -0.66]}
          scale={[0.74, 0, 2.11]}
        />
        <mesh
          geometry={nodes.Wall33.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-3.12, 2.22, 0.21]}
          rotation={[0, 0, -0.66]}
          scale={[2.16, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Opening0.geometry}
          material={materials.Opening0_color}
          position={[-2.03, 1.87, 0.43]}
          rotation={[0, 0, 0.92]}
          scale={[0.78, 0, 2.1]}
        />
        <mesh
          geometry={nodes.Wall34.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-1.82, 2.14, 0.21]}
          rotation={[0, 0, 0.92]}
          scale={[1.46, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Opening0001.geometry}
          material={materials.Opening0_color}
          position={[-3.72, 3.19, 0.44]}
          rotation={[0, 0, 0.9]}
          scale={[0.8, 0, 2.08]}
        />
        <mesh
          geometry={nodes.Wall35.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-3.51, 3.46, 0.21]}
          rotation={[0, 0, 0.9]}
          scale={[1.48, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Door0001.geometry}
          material={materials.Door0_color}
          position={[-9.44, -1.45, 0.45]}
          rotation={[0, 0, -0.67]}
          scale={[0.77, 0, 2.07]}
        />
        <mesh
          geometry={nodes.Wall36.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-10.11, -0.93, 0.21]}
          rotation={[0, 0, -0.67]}
          scale={[4.69, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Opening0002.geometry}
          material={materials.Opening0_color}
          position={[0.71, -0.69, 0.43]}
          rotation={[0, 0, 0.9]}
          scale={[1.36, 0, 2.1]}
        />
        <mesh
          geometry={nodes.Wall37.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-0.27, -1.93, 0.21]}
          rotation={[0, 0, 0.9]}
          scale={[4.5, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Window0002.geometry}
          material={materials.Window0_color}
          position={[-0.87, -2.69, -0.34]}
          rotation={[0, 0, 0.9]}
          scale={[2.22, 0, 0.7]}
        />
        <mesh
          geometry={nodes.Opening0003.geometry}
          material={materials.Opening0_color}
          position={[-2.32, 0.84, 0.42]}
          rotation={[0, 0, -0.74]}
          scale={[1.27, 0, 2.12]}
        />
        <mesh
          geometry={nodes.Wall38.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-2.04, 0.58, 0.21]}
          rotation={[0, 0, -0.74]}
          scale={[2.03, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall3.geometry}
          material={wallMaterial}
          name="Wall"
          position={[1.39, 1.65, 0.21]}
          rotation={[0, 0, 2.48]}
          scale={[1.81, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall4.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-10.48, 3.21, 0.21]}
          rotation={[0, 0, -0.67]}
          scale={[0.92, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall5.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-8.06, 2.19, 0.21]}
          rotation={[0, 0, -0.67]}
          scale={[1.49, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall6.geometry}
          material={wallMaterial}
          name="Wall"
          position={[0.19, 1.58, 0.21]}
          rotation={[0, 0, 0.9]}
          scale={[1.58, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall7.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-7.7, 1.45, 0.21]}
          rotation={[0, 0, -2.24]}
          scale={[0.71, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall8.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-8.87, 2.38, 0.21]}
          rotation={[0, 0, 0.89]}
          scale={[0.7, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Wall9.geometry}
          material={wallMaterial}
          name="Wall"
          position={[-7.26, -1.2, 0.21]}
          rotation={[0, 0, 0.87]}
          scale={[3.09, 0, 2.55]}
        />
        <mesh
          geometry={nodes.Bed0.geometry}
          material={materials.Bed0_color}
          position={[-2.29, -1.88, 1.15]}
          rotation={[0, 0, -0.67]}
          scale={[1.85, 2.07, 0.67]}
        />
        <mesh
          geometry={nodes.Chair0.geometry}
          material={materials.Chair0_color}
          position={[-9.67, 0.94, 1.17]}
          rotation={[0, 0, 2.49]}
          scale={[0.47, 0.52, 0.62]}
        />
        <mesh
          geometry={nodes.Chair1.geometry}
          material={materials.Chair1_color}
          position={[-10.25, 1.39, 1.17]}
          rotation={[0, 0, 2.49]}
          scale={[0.47, 0.52, 0.62]}
        />
        <mesh
          geometry={nodes.Chair2.geometry}
          material={materials.Chair2_color}
          position={[-9.09, 0.5, 1.17]}
          rotation={[0, 0, 2.49]}
          scale={[0.47, 0.52, 0.62]}
        />
        <mesh
          geometry={nodes.Chair3.geometry}
          material={materials.Chair3_color}
          position={[-11.69, -1.02, 1.12]}
          rotation={[0, 0, -2.24]}
          scale={[0.65, 0.75, 0.72]}
        />
        <mesh
          geometry={nodes.Dishwasher0.geometry}
          material={materials.Dishwasher0_color}
          position={[-6.57, 0.47, 1.05]}
          rotation={[0, 0, 0.87]}
          scale={[0.71, 0.61, 0.87]}
        />
        <mesh
          geometry={nodes.Oven0.geometry}
          material={materials.Oven0_color}
          position={[-8.07, -1.58, 1.07]}
          rotation={[0, 0, 0.87]}
          scale={[0.72, 0.74, 0.83]}
        />
        <mesh
          geometry={nodes.Refrigerator0.geometry}
          material={materials.Refrigerator0_color}
          position={[-8.53, 1.53, 0.52]}
          rotation={[0, 0, 2.48]}
          scale={[0.99, 0.21, 1.92]}
        />
        <mesh
          geometry={nodes.Sink0.geometry}
          material={materials.Sink0_color}
          position={[-7.23, -0.35, 0.72]}
          rotation={[0, 0, 0.87]}
          scale={[0.43, 0.4, 0.22]}
        />
        <mesh
          geometry={nodes.Sofa0.geometry}
          material={materials.Sofa0_color}
          position={[-7.94, 3.4, 1.03]}
          rotation={[0, 0, -0.67]}
          scale={[3.61, 1.24, 0.9]}
        />
        <mesh
          geometry={nodes.Sofa1.geometry}
          material={materials.Sofa1_color}
          position={[-6.39, 3.34, 1.16]}
          rotation={[0, 0, 0.9]}
          scale={[0.6, 1.14, 0.65]}
        />
        <mesh
          geometry={nodes.Sofa2.geometry}
          material={materials.Sofa2_color}
          position={[-8.06, 5.28, 1.03]}
          rotation={[0, 0, -2.24]}
          scale={[1.56, 1.18, 0.9]}
        />
        <mesh
          geometry={nodes.Storage0.geometry}
          material={materials.Storage0_color}
          position={[-1.15, -0.63, 0.93]}
          rotation={[0, 0, 2.48]}
          scale={[1.41, 0.65, 1.1]}
        />
        <mesh
          geometry={nodes.Storage1.geometry}
          material={materials.Storage1_color}
          position={[-11.82, -2.49, 0.34]}
          rotation={[0, 0, -0.67]}
          scale={[1.15, 0.27, 2.29]}
        />
        <mesh
          geometry={nodes.Storage10.geometry}
          material={materials.Storage10_color}
          position={[-5.7, 1.12, 0.99]}
          rotation={[0, 0, 0.9]}
          scale={[1.12, 0.55, 0.99]}
        />
        <mesh
          geometry={nodes.Storage11.geometry}
          material={materials.Storage11_color}
          position={[-0.75, 1.95, 0.34]}
          rotation={[0, 0, 2.49]}
          scale={[1.93, 0.65, 2.29]}
        />
        <mesh
          geometry={nodes.Storage12.geometry}
          material={materials.Storage12_color}
          position={[-8.79, -2.37, 0.32]}
          rotation={[0, 0, 0.9]}
          scale={[0.63, 0.57, 2.33]}
        />
        <mesh
          geometry={nodes.Storage13.geometry}
          material={materials.Storage13_color}
          position={[-5.67, 5.79, 1.1]}
          rotation={[0, 0, 2.48]}
          scale={[1.81, 0.47, 0.77]}
        />
        <mesh
          geometry={nodes.Storage2.geometry}
          material={materials.Storage2_color}
          position={[-3.81, 4.38, 0.52]}
          rotation={[0, 0, 2.48]}
          scale={[1.61, 0.4, 1.93]}
        />
        <mesh
          geometry={nodes.Storage3.geometry}
          material={materials.Storage3_color}
          position={[-7.34, -0.53, 1.05]}
          rotation={[0, 0, 0.87]}
          scale={[1.81, 0.61, 0.87]}
        />
        <mesh
          geometry={nodes.Storage4.geometry}
          material={materials.Storage4_color}
          position={[-4.42, 1.98, -0.27]}
          rotation={[0, 0, -2.24]}
          scale={[1.47, 0.41, 0.8]}
        />
        <mesh
          geometry={nodes.Storage5.geometry}
          material={materials.Storage5_color}
          position={[-12.5, -1.92, 1.1]}
          rotation={[0, 0, -0.67]}
          scale={[0.94, 0.32, 0.76]}
        />
        <mesh
          geometry={nodes.Storage6.geometry}
          material={materials.Storage6_color}
          position={[-7.34, -0.67, -0.47]}
          rotation={[0, 0, 0.87]}
          scale={[3.44, 0.47, 1.09]}
        />
        <mesh
          geometry={nodes.Storage7.geometry}
          material={materials.Storage7_color}
          position={[-8.38, -1.97, 1.05]}
          rotation={[0, 0, 0.9]}
          scale={[0.29, 0.71, 0.87]}
        />
        <mesh
          geometry={nodes.Storage8.geometry}
          material={materials.Storage8_color}
          position={[-10.37, 3.37, 0.36]}
          rotation={[0, 0, -0.67]}
          scale={[0.88, 0.37, 2.24]}
        />
        <mesh
          geometry={nodes.Storage9.geometry}
          material={materials.Storage9_color}
          position={[-2.02, 3.08, 0.29]}
          rotation={[0, 0, 2.48]}
          scale={[0.47, 0.22, 0.67]}
        />
        <mesh
          geometry={nodes.Table0.geometry}
          material={materials.Table0_color}
          position={[-9.78, 3.03, 1.13]}
          rotation={[0, 0, -2.24]}
          scale={[0.58, 0.48, 0.7]}
        />
        <mesh
          geometry={nodes.Table1.geometry}
          material={materials.Table1_color}
          position={[-11.27, -0.49, 1.03]}
          rotation={[0, 0, 2.48]}
          scale={[1.75, 0.75, 0.9]}
        />
        <mesh
          geometry={nodes.Table2.geometry}
          material={materials.Table2_color}
          position={[-3.76, -1.83, 1.12]}
          rotation={[0, 0, -0.67]}
          scale={[0.52, 0.34, 0.72]}
        />
        <mesh
          geometry={nodes.Table3.geometry}
          material={materials.Table3_color}
          position={[-2.4, 3.11, 1.02]}
          rotation={[0, 0, 2.48]}
          scale={[1.65, 0.63, 0.92]}
        />
        <mesh
          geometry={nodes.Table4.geometry}
          material={materials.Table4_color}
          position={[-9.9, 0.64, 1.1]}
          rotation={[0, 0, 2.49]}
          scale={[2.19, 0.91, 0.77]}
        />
        <mesh
          geometry={nodes.Table5.geometry}
          material={materials.Table5_color}
          position={[-1.9, -3.29, 1.13]}
          rotation={[0, 0, -0.67]}
          scale={[0.57, 0.34, 0.7]}
        />
        <mesh
          geometry={nodes.Table6.geometry}
          material={materials.Table6_color}
          position={[-7.36, 4.3, 1.24]}
          rotation={[0, 0, -0.67]}
          scale={[1.11, 0.94, 0.48]}
        />
        <mesh
          geometry={nodes.Television0.geometry}
          material={materials.Television0_color}
          position={[-2.15, 3.08, 0.25]}
          rotation={[0, 0, 2.48]}
          scale={[0.83, 0.1, 0.52]}
        />
        <mesh
          geometry={nodes.Television1.geometry}
          material={materials.Television1_color}
          position={[-11.32, -0.45, 0.38]}
          rotation={[0, 0, 2.48]}
          scale={[0.7, 0.1, 0.48]}
        />
        <mesh
          geometry={nodes.Television2.geometry}
          material={materials.Television2_color}
          position={[-5.57, 5.91, 0.27]}
          rotation={[0, 0, 2.48]}
          scale={[1.22, 0.17, 0.75]}
        />
        <mesh
          geometry={nodes.Washerdryer0.geometry}
          material={materials.Washerdryer0_color}
          position={[-4.22, 2, 1.02]}
          rotation={[0, 0, -2.24]}
          scale={[0.65, 0.7, 0.93]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3d/myroom.glb");
